### ISSUE TITLE
Rescue Time Tracker

### ISSUE THREAD

**Issue by Merovex** [verkilo/verkilo#3]
Integrate Rescue Time into Verkilo tracking so we can calculate total time writing and words-per-hour.

Problem is if there are multiple series...may not be viable.

## GH Action

- [ ] Create Cron Action, cloning the Wordcounter...or add as step for one 
- [ ] Run Docker...multiple repositories?
- [ ] Commit change to Develop
- [ ] Do I need a separate repository to track this?

## Docker

- [ ] Create Docker Repo
- [ ] Get date range from processing the wordcount.yml file
- [ ] Pull times in date range
- [ ] Populate `rescuetime.yml` file
